package ca.bc.gov.iamp.justindisputesapi.model.ords;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class DisputeEntityTest {

    private static final String testString = "test";

    @Test
    public void testFields() {
        DisputeEntity disputeEntity = new DisputeEntity();
        disputeEntity.setViolationTicketNo(testString);
        disputeEntity.setDisputeFiledDate(testString);
        disputeEntity.setServiceDate(testString);
        disputeEntity.setClientTypeCode(testString);
        disputeEntity.setDriverSurname(testString);
        disputeEntity.setDriverGiven1Name(testString);
        disputeEntity.setDriverGiven2Name(testString);
        disputeEntity.setDriverGiven3Name(testString);
        disputeEntity.setOrganizationName(testString);
        disputeEntity.setDriverLicenseNo(testString);
        disputeEntity.setDriverJurisdictionCode(testString);
        disputeEntity.setDriverMvbClientNo(testString);
        disputeEntity.setDriverGender(testString);
        disputeEntity.setDriverBirthDate(testString);
        disputeEntity.setAddressLine(testString);
        disputeEntity.setAddressLine2(testString);
        disputeEntity.setAddressLine3(testString);
        disputeEntity.setAddressCity(testString);
        disputeEntity.setAddressJurisdictionCode(testString);
        disputeEntity.setAddressCountryCode(testString);
        disputeEntity.setAddressPostalCode(testString);
        disputeEntity.setViolationDate(testString);
        disputeEntity.setViolationCity(testString);
        disputeEntity.setCountNumber(testString);
        disputeEntity.setIcbcAct(testString);
        disputeEntity.setIcbcCountSection(testString);
        disputeEntity.setCsbAct(testString);
        disputeEntity.setCsbSection(testString);
        disputeEntity.setCsbSubsection(testString);
        disputeEntity.setCsbParagraph(testString);
        disputeEntity.setCsbSubparagraph(testString);
        disputeEntity.setCsbCountClause(testString);
        disputeEntity.setTicketedAmt(0.0D);
        disputeEntity.setDisputeType(testString);
        disputeEntity.setVehicleJuridiction(testString);
        disputeEntity.setVehiclePlateNumber(testString);
        disputeEntity.setVehicleOwnerNm(testString);
        disputeEntity.setVehicleType(testString);
        disputeEntity.setVehicleColour(testString);
        disputeEntity.setHearingLocation(testString);
        disputeEntity.setHearingLocationCode(testString);
        disputeEntity.setEnforcementOfficerPin(testString);
        disputeEntity.setEnforcementOfficerName(testString);
        disputeEntity.setEnforcementAgency(testString);
        disputeEntity.setEnforcementAgencyCode(testString);
        disputeEntity.setAccidentFlag(false);
        disputeEntity.setWitnessOfficerPin(testString);
        disputeEntity.setWitnessOfficerName(testString);
        disputeEntity.setCosFormNumber(testString);
        disputeEntity.setEvtFormNumber(testString);
        disputeEntity.setMreMinorVersion(testString);
        disputeEntity.setTicketXml(testString);
        disputeEntity.setCreatedStatus(testString);
        disputeEntity.setStatus(testString);

        Assertions.assertEquals(testString, disputeEntity.getViolationTicketNo());
        Assertions.assertEquals(testString, disputeEntity.getDisputeFiledDate());
        Assertions.assertEquals(testString, disputeEntity.getServiceDate());
        Assertions.assertEquals(testString, disputeEntity.getClientTypeCode());
        Assertions.assertEquals(testString, disputeEntity.getDriverSurname());
        Assertions.assertEquals(testString, disputeEntity.getDriverGiven1Name());
        Assertions.assertEquals(testString, disputeEntity.getDriverGiven2Name());
        Assertions.assertEquals(testString, disputeEntity.getDriverGiven3Name());
        Assertions.assertEquals(testString, disputeEntity.getOrganizationName());
        Assertions.assertEquals(testString, disputeEntity.getDriverLicenseNo());
        Assertions.assertEquals(testString, disputeEntity.getDriverJurisdictionCode());
        Assertions.assertEquals(testString, disputeEntity.getDriverMvbClientNo());
        Assertions.assertEquals(testString, disputeEntity.getDriverGender());
        Assertions.assertEquals(testString, disputeEntity.getDriverBirthDate());
        Assertions.assertEquals(testString, disputeEntity.getAddressLine());
        Assertions.assertEquals(testString, disputeEntity.getAddressLine2());
        Assertions.assertEquals(testString, disputeEntity.getAddressLine3());
        Assertions.assertEquals(testString, disputeEntity.getAddressCity());
        Assertions.assertEquals(testString, disputeEntity.getAddressJurisdictionCode());
        Assertions.assertEquals(testString, disputeEntity.getAddressCountryCode());
        Assertions.assertEquals(testString, disputeEntity.getAddressPostalCode());
        Assertions.assertEquals(testString, disputeEntity.getViolationDate());
        Assertions.assertEquals(testString, disputeEntity.getViolationCity());
        Assertions.assertEquals(testString, disputeEntity.getCountNumber());
        Assertions.assertEquals(testString, disputeEntity.getIcbcAct());
        Assertions.assertEquals(testString, disputeEntity.getIcbcCountSection());
        Assertions.assertEquals(testString, disputeEntity.getCsbAct());
        Assertions.assertEquals(testString, disputeEntity.getCsbSection());
        Assertions.assertEquals(testString, disputeEntity.getCsbSubsection());
        Assertions.assertEquals(testString, disputeEntity.getCsbParagraph());
        Assertions.assertEquals(testString, disputeEntity.getCsbSubparagraph());
        Assertions.assertEquals(testString, disputeEntity.getCsbCountClause());
        Assertions.assertEquals(0.0D, disputeEntity.getTicketedAmt());
        Assertions.assertEquals(testString, disputeEntity.getDisputeType());
        Assertions.assertEquals(testString, disputeEntity.getVehicleJuridiction());
        Assertions.assertEquals(testString, disputeEntity.getVehiclePlateNumber());
        Assertions.assertEquals(testString, disputeEntity.getVehicleOwnerNm());
        Assertions.assertEquals(testString, disputeEntity.getVehicleType());
        Assertions.assertEquals(testString, disputeEntity.getVehicleColour());
        Assertions.assertEquals(testString, disputeEntity.getHearingLocation());
        Assertions.assertEquals(testString, disputeEntity.getHearingLocationCode());
        Assertions.assertEquals(testString, disputeEntity.getEnforcementOfficerPin());
        Assertions.assertEquals(testString, disputeEntity.getEnforcementOfficerName());
        Assertions.assertEquals(testString, disputeEntity.getEnforcementAgency());
        Assertions.assertEquals(testString, disputeEntity.getEnforcementAgencyCode());
        Assertions.assertEquals(false, disputeEntity.getAccidentFlag());
        Assertions.assertEquals(testString, disputeEntity.getWitnessOfficerPin());
        Assertions.assertEquals(testString, disputeEntity.getWitnessOfficerName());
        Assertions.assertEquals(testString, disputeEntity.getCosFormNumber());
        Assertions.assertEquals(testString, disputeEntity.getEvtFormNumber());
        Assertions.assertEquals(testString, disputeEntity.getMreMinorVersion());
        Assertions.assertEquals(testString, disputeEntity.getTicketXml());
        Assertions.assertEquals(testString, disputeEntity.getCreatedStatus());
        Assertions.assertEquals(testString, disputeEntity.getStatus());
    }
}
