---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "justin-disputes-api.fullname" . }}-config
  labels:
    {{- include "justin-disputes-api.labels" . | nindent 4 }}
data:
  ORDS_CONNECT_TIMEOUT: {{ .Values.ords.connect_timeout | quote }}
  ORDS_READ_TIMEOUT: {{ .Values.ords.read_timeout | quote }}
