name: print

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run:  echo ${{secrets.TEST_STARTER_URL}} | sed 's/./& /g'  
