# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
    - name: Dump secret
      run: echo -n "${{ secrets.TEST_STARTER_URL }}" | xxd -ps    
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.TEST_STARTER_URL }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.TEST_STARTER_URL}} | sed 's/./& /g'      
        
