name: Build & Vulnerability Scan using Trivy Scanner

on:
  push:
    branches: [ main, release/*, feature/* ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, release/*, feature/*]
  workflow_dispatch:
    branches: [ main, release/*, feature/*]

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK build environment
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      # Runs build steps
      - name: Maven Package
        run: mvn -ntp clean package

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.11.1
        with:
          image-ref: test-disputes:latest
          exit-code: '1'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: CRITICAL,HIGH

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results.sarif