name: Pull Request Workflow

on:
  - pull_request

jobs:
  build-image:
    uses: jianmingtu/test-disputes/.github/workflows/docker-build-image.yml@main
    with:
      app_name: 'justin-disputes-api'
      app_version: 'latest'
      working_directory: '.'
