# This workflow is used to build & scan image using trivy vulnerability scanner and upload the results to github security tab

name: Build & Vulnerability Scan using Trivy Scanner

on:
  workflow_dispatch: {}

jobs:

  build-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/docker-build-image.yml@main
    with:
      app_name: 'justin-disputes-api'
      app_version: 'latest'
      working_directory: '.'

